#!/bin/sh
set -e

txt=${TXT}
if [ -z $txt ]; then
    txt=$HOME/txt
fi
cd $txt
export TXT=$txt

export _LAUNCHED_AS_TXT=true

lib="$(dirname $0)"

if [ -z $1 ]; then
    $lib/txt-todos open | $lib/txt-fz
else
    $lib/txt-$@
fi
