#!/usr/bin/env python3
import sys

if len(sys.argv) != 3:
  print("incorrect args")
  exit(-1)

file = sys.argv[1]
number = int(sys.argv[2])

def find_indent(line):
  indent=0
  for c in line:
    if c == ' ' or c == '\t':
      indent += 1
      continue
    else:
      break
  return indent

indent=0
innode = False
n = 0
with open(file) as f:
  while line := f.readline():
    line = line.rstrip()
    n += 1
    current_indent = find_indent(line)
    if n == number:
      print(line)
      indent=current_indent
      innode = True
      continue
    if innode and current_indent > indent:
      print(line)
      continue
    if innode and current_indent <= indent:
      break
