#!/bin/sh
set -e

case $1 in
    "todo") grep -irn '\- \[ \]' *
    	;;
    "m") grep -irn '\- \[m\]' *
    	;;
    "done") grep -irn '\- \[x\]' *
    	;;
    "open") grep -irn '\- \[[^x]\]' *
           ;;
    "all") grep -irn '\- \[.\]' *
           ;;
    *) grep -irn "\- \[$1\]" *
esac
